repos:
  # Nettoyage de base des fichiers texte et code
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace       # Supprime les espaces inutiles en fin de ligne
      - id: end-of-file-fixer         # S'assure que chaque fichier se termine par une nouvelle ligne
      - id: check-yaml                # Vérifie la syntaxe des fichiers YAML
      - id: check-docstring-first     # S'assure que la docstring est placée au bon endroit
      - id: detect-private-key        # Détecte les clés privées dans le code pour éviter les fuites de sécurité
      - id: check-case-conflict       # Vérifie les conflits de casse dans les noms de fichiers pour éviter les problèmes sur différents systèmes de fichiers

  # Linting et Formatage du code Python avec Ruff (Ultra-rapide)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.0
    hooks:
      # Linter : Détecte les variables non utilisées, imports cassés, etc.
      - id: ruff
        args: [--fix]
      # Formatter : Formate automatiquement le code selon la norme PEP8
      - id: ruff-format
